### PR TITLE
Update UnixProcessesService.java

### PR DESCRIPTION
**Pull request by jkuharev**
Unix/BSD/Mac compatibility

### CODE REVIEW

**Comment by profesorfalken** [comment]
Thank you very much for your refactoring, but we should be careful with this: 
_element.put( "proc_name", element.get( "command" ) );_

Since the proc name (comm) is not the same than the command (command). 
Par exemple le command ps -e.
comm: ps
command: ps -e

**Comment by profesorfalken** [comment]
I do not understand also this line:
"ps -e -o " + PS_COLUMNS + " | grep \"" + name + "\" | grep -v \"grep " + name + "\""

Could you explain it please?

If I try to seach the process 'java' it will not return also the process called 'javatest"

**Comment by jkuharev** [comment]
> "ps -e -o " + PS_COLUMNS + " | grep \"" + name + "\" | grep -v \"grep " + name + "\”"

first grep finds lines with the name including the line with the "grep name”
the second one excludes the “grep name” from result

> Since the proc name (comm) is not the same than the command (command).
> Par exemple le command ps -e.
> comm: ps
> command: ps -e

Yes, comm and command are different.
The problem is that ps will crop the first one of them,
and you see in case of pid 49 and 54 it results in the same comm but the binary is not the same
like that:

>ps -eo pid,comm,command
  PID COMM             COMMAND
    1 /sbin/launchd    /sbin/launchd
   45 /usr/sbin/syslog /usr/sbin/syslogd
   46 /usr/libexec/Use /usr/libexec/UserEventAgent (System)
   48 /usr/libexec/kex /usr/libexec/kextd
   49 /System/Library/ /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/Support/fseventsd
   54 /System/Library/ /System/Library/CoreServices/appleeventsd --server


On Feb 23, 2016, at 10:57, JGA <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not understand also this line:
"ps -e -o " + PS_COLUMNS + " | grep \"" + name + "\" | grep -v \"grep " + name + "\""

Could you explain it please?

If I try to seach the process 'java' it will not return also the process called 'javatest"

**Comment by jkuharev** [comment]
to retrieve both strings comm and command,
we could run ps twice
e.g.
> ps -e -o pid,…comm
and just ps -e -o pid,command
then join them by pid in Java

ok, some processes may disappear and some new may appear during the second ps,
so only intersecting processes should be kept in the list

**Comment by profesorfalken** [comment]
> first grep finds lines with the name including the line with the "grep name”
the second one excludes the “grep name” from result

In that case we agree that it is not correct. The target of this method is to search a list of process with a specific name and not to perform a generic grep on ps command.

Ouch, in fact I have seen that with the change done yesterday in the columns I broke everything. I will have to revert it...

**Comment by profesorfalken** [comment]
Done. Fixed column numbers.

In relation with comm and command in fact in linux it does exactly what I wanted. comm is the name of the process and command is the full executable without the parameters (maybe I will include the parameters in another field in other version)

    ps -e o comm,command | grep chrome

    chrome          /opt/google/chrome/chrome --type=renderer --lang[......]
    .....

**Comment by jkuharev** [comment]
What happens with executables having spaces in their names like "Image Capture"
or having very long names like "lightdm-gtk-greeter"?
Spaces are a problem for parsing, long names are croped.

To harmonize the behavior of name displaying on Linux and BSD 
ps we could use ucomm instead of "comm".
Ucom seems to display only the executable name on both types of ps:
See man pages (http://www.manpages.info/linux/ps.1.html) and (http://www.freebsd.org/cgi/man.cgi?query=ps)
also the output on my Mac and Linux looks good for that.

**Comment by profesorfalken** [comment]
That's really cool, I will take it a look tonight after work.

Thank you very much again.

**Comment by profesorfalken** [comment]
Ok for ucomm. 
The problem with the spaces and the long names is harder. I am trying to figure out how to handle it.

**Comment by profesorfalken** [comment]
To avoid the crop it is clear that we should use a kind of intersecting solution as you propose. I will try something this weekend for a possible v1.2

**Comment by profesorfalken** [comment]
Hello again, 

I have just created the 1.2 version. The full command is obtained intersecting as you suggested and the process name search is made manually looping the list when it is not a Linux system so we do not have available the ps -C command. 

Could you check if it is ok on Mac? Thanks a lot for your help!

PD: however I do not know how to solve the problem of 15 characters limitation on process name. Even when doing a cat /prod/PID/comm... the name seems to be truncated already at kernel level :-(
Do you have any idea?

**Comment by jkuharev** [comment]
Hello Javier, sorry for the delay ...

I see some general problems again:
1. 
The command ps shaped as 
"ps o HEREBECOLUMNS -e" does not properly work on a mac, while 
"ps -e o HEREBECOLUMNS" does work and
"ps -o HEREBECOLUMNS -e" does work as well,
I actually prefer to put all switches in their logical order before columns:
"ps -e -o HEREBECOLUMNS"
with the meaning of "select all processes and then format the output"

2.
if the first column is text e.g. ucomm we end up in wrongly parsing the string
example "GitHub Desktop" ...
Output:
PID:Desktop	CPU:123876	MEM:3747456	PRIORITY:0:12.74	CMD:0 /Applications/Developer/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
...
The only solution is to avoid text columns at the beginning of the line.

I already started fix this probelms and will post my tested solution tomorrow

cheers Jörg

**Comment by profesorfalken** [comment]
Cool, thank you!

**Comment by profesorfalken** [comment]
Closed as it is done in other pull request here: [#4](https://github.com/profesorfalken/jProcesses/pull/6)

**Pull request closed without merging**
